### ISSUE TITLE
Smooth volume updates and other suggested features

### ISSUE THREAD

**Issue by ghost** [RubenSandwich/codeflow#1]
Hello! I recently switched to using vscode to develop my Unreal Engine 4 games and I'm really glad I did. I decided to try out codeflow because I like to listen to music while I code and the idea seems really cool.

The experience I have with it is amazing. As I start to code, my music gets louder until it gets to full blast and I'm completely in the zone. I don't need to touch my volume, I just need to code. It's awesome. But I have some suggestions.

### Smooth volume updating

I don't know much about VS Code extension development so I don't know if this is possible, but one idea I have is a setting that, if enabled, codeflow will update the volume like this:

 - track the keyboard input to get the typing speed using the configured update interval to determine how long to track
 - when the interval is hit, determine how much to increase/decrease the volume
 - slowly increase/decrease the volume over the next interval WHILE tracking keyboard speed.
 - wash, rinse, repeat.

If all goes well, what should happen is, instead of codeflow just setting the volume every few seconds, it creates a smooth transition. That way, large volume changes are nowhere near as distracting because it's like a nice fade instead of a sudden cut.

### Don't decrease the volume while a build task is in progress

C++ projects take a bit longer to build than projects in other languages - especially Unreal projects :)

So, while waiting for the build to complete, what would be cool is if the music stays at its current volume. In my opinion this would create a sense of suspense - "will it compile? are there errors? did I mess up? Did I do it right!?".

Then you can do things like, if the build task fails, the music volume fastly decreases to minimum volume indicating that the code didn't compile or whatnot. And if the build task completes, the music rises up to max volume - which theoretically might release a rush of adrenaline and dopamine.

Of course, this could also be a setting that can be enabled or disabled, but it's a neat idea in my opinion.

### Add a buffer between "fever" states and idle states.

By "fever" states I mean when the volume rises up to max and stays there consistently. When you detect the end of a "fever," i.e the coder slowed down (and maybe went over to the Explorer to make a file), add a buffer between the end of this "fever" and the start of the volume decreasing. This gives the coder some time to create a file in the Explorer, run a command, etc., without it seeming like they broke their flow. If the time buffer hits, then logic would state that the coder actually did break their flow.

Perhaps this could also be a setting, both whether the buffer's enabled and how long it is.

### Conclusion

Anyway, those are just some of my ideas for features that could be added to this. So far it's a really cool extension and I definitely recommend it to any music-loving programmers out there.

The only other feature I would add is actually detecting a "fever" mode and displaying some visual effects on the edges of the screen to the beat of the music, pulsing the coder's RGB setup red based on the beat, etc., but that has nothing to do with what this extension is about and would have to be programmed to work specifically for that system or it would take a lot more effort. (You'd actually need to do audio processing for that stuff.) And I'd probably be the only one to use it, lol.

**Comment by RubenSandwich** [comment]
Hey @alkalinethunder,

I'm happy that this extension is helping keep you in a focused state. I'll address some of your suggestions:

### **Smooth volume updating & Add a buffer between "fever" states and idle states.**

I agree that this is needed. I tried to fix this issue by determining the volume to set on a logarithmic scale. (https://github.com/RubenSandwich/codeflow/blob/master/src/extension.ts#L137) However, the problem with that is logarithms can be quite steep to start out, so while the changes are "unnoticeable" while you're close to the max volume the first few changes can be quite drastic.

I think your right on the money with this:
> slowly increase/decrease the volume over the next interval WHILE tracking keyboard speed.

Overall I'm not super happy with the current strategy of adjusting the volume. (I'm gonna also do some research on how DJ software blends two tracks as I feel that might be helpful to this situation.) I also want to look into ways to make volume decay slower as well as we all take small pauses to think and that shouldn't be penalized. (What you better describe as fever states.)


### **Don't decrease the volume while a build task is in progress**
I agree completely with this. I also need to factor in terminal input into "velocity". I'm guessing you're using the VSCode tasks to build right? (Because looking at the API it looks like I can easily listen for task's start and end events: https://code.visualstudio.com/docs/extensionAPI/vscode-api#_tasks.) 

I'm asking that because I'm not sure off the top of my head how to watch the terminal for when a build finishes. (For example, how would you distinguish a build from standard Unix commands besides watching certain predefined terminal commands and waiting till the terminal can respond again. But that doesn't scale as depending on the language community build tools can change yearly.)


### **The only other feature I would add is actually detecting a "fever" mode and displaying some visual effects on the edges of the screen to the beat of the music, pulsing the coder's RGB setup red based on the beat, etc.**
I agree that fever states should be rewarded in some way. I'm not sure yet how. I like your idea of some real-world feedback, but doubt how possible it would be in VSCode. They make a pretty good attempt to lock down extensions into a sandbox. (See my dirty way to adjusting volume by running terminal commands on your machine. I honestly half expected this extension to be removed/rejected for doing that.) Listening to the beat would also require some way to listen to the input music, which would meaning building a competent music player. I'll think a bit more about this.

I will let you know where I want to go with this extension. I started working on this extension to play with the idea of passive biological rhythm, using your body's normal movement to passively generate music. (Sort of the idea of "what if life had a soundtrack".) This is an MVP of that idea, as I'm currently just using volume. But I'm happy to hear that even this MVP resonates with you. I got more planned for this.

Thanks again for all the feedback, I'm super excited you took the time to write this. I'm a bit busy at work at the moment, but over the next few weeks, I'll spend some time on implementing these features.

P.S. If you could rate the extension I'd really appreciate it as it helps with the VSCode's marketplace discoverability. Please and thank you. 🙏🏽

**Comment by RubenSandwich** [comment]
@alkalinethunder

I just updated codeflow. Sorry for the wait. It now pauses when any debug builds or tasks are active in VS Code. It also works on a new volume range system. Instead of setting the minimum and maximum volume, you now provide codeflow with a range and it changes your volume based on that amount.

I'll work on smooth volume updating in the next update. (Adding an issue for smooth volume updating now.)
